"""Cambio al modelo de Nodo

Revision ID: c3a1ef3e650f
Revises: 
Create Date: 2025-03-16 19:48:30.690289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a1ef3e650f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodos', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
