"""Cambio: agregar atributos para cambios personalizables en nodos

Revision ID: fb461c92b28f
Revises: 248bd65c610d
Create Date: 2025-03-21 23:34:59.569095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb461c92b28f'
down_revision = '248bd65c610d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_bg', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('color_border', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('color_text', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodos', schema=None) as batch_op:
        batch_op.drop_column('color_text')
        batch_op.drop_column('color_border')
        batch_op.drop_column('color_bg')

    # ### end Alembic commands ###
